http:
  routers:
    shell:
      rule: "Host(`shell.ailab.lan`)"
      entryPoints:
        - https
      service: shell
      tls: true
    ollama:
      rule: "Host(`ollama.ailab.lan`)"
      entryPoints:
        - https
      service: ollama
      tls: true

  services:
    shell:
      loadBalancer:
        servers:
          - url: "http://ollama:8080"
    ollama:
      loadBalancer:
        servers:
          - url: "http://ollama:11434"
